[package]
name = "frequenz-microgrid-component-graph"
description = "A library for representing the components of a microgrid and the connections between them as a Directed Acyclic Graph (DAG)."
version = "0.3.0"
edition = "2024"
repository = "https://github.com/frequenz-floss/frequenz-microgrid-component-graph-rs"
license = "MIT"

[lib]
name = "frequenz_microgrid_component_graph"
path = "src/lib.rs"

[dependencies]
petgraph = "0.6.5"
tracing = "0.1.40"
