// License: MIT
// Copyright © 2025 Frequenz Energy-as-a-Service GmbH

//! This module defines the `Formula` struct and its operations.

use super::expr::Expr;

// This struct represents the microgrid metric formulas that are generated by
// traversing the component graph.
//
// `Formula` objects can be added or subtracted from each other, and they can
// converted to a string representation, before they are passed to an evaluator.
#[derive(Debug, Clone, PartialEq)]
pub struct Formula {
    expr: Expr,
}

impl Formula {
    pub(crate) fn new(expr: Expr) -> Self {
        Formula { expr }
    }
}

impl std::ops::Add for Formula {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        Formula {
            expr: self.expr + rhs.expr,
        }
    }
}

impl std::ops::Sub for Formula {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        Formula {
            expr: self.expr - rhs.expr,
        }
    }
}

impl std::fmt::Display for Formula {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.expr.fmt(f)
    }
}

impl From<Formula> for String {
    fn from(formula: Formula) -> Self {
        formula.expr.to_string()
    }
}
