// License: MIT
// Copyright © 2025 Frequenz Energy-as-a-Service GmbH

//! This module defines the `Formula` struct and its operations.

use super::expr::Expr;

// This struct represents the microgrid metric formulas that are generated by
// traversing the component graph.
//
// They are used to represent quantities that are aggregated over multiple
// components in the microgrid, such as power or current.
//
// `AggregationFormula` objects can be added or subtracted from each other, and
// they can converted to a string representation, before they are passed to an
// evaluator.
#[derive(Debug, Clone, PartialEq)]
pub struct AggregationFormula {
    expr: Expr,
}

impl From<Expr> for AggregationFormula {
    fn from(expr: Expr) -> Self {
        AggregationFormula { expr }
    }
}

impl From<AggregationFormula> for Expr {
    fn from(formula: AggregationFormula) -> Self {
        formula.expr
    }
}

impl AggregationFormula {
    pub(crate) fn new(expr: Expr) -> Self {
        AggregationFormula { expr }
    }
}

impl std::ops::Add for AggregationFormula {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        AggregationFormula {
            expr: self.expr + rhs.expr,
        }
    }
}

impl std::ops::Sub for AggregationFormula {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        AggregationFormula {
            expr: self.expr - rhs.expr,
        }
    }
}

impl std::fmt::Display for AggregationFormula {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.expr.fmt(f)
    }
}

impl From<AggregationFormula> for String {
    fn from(formula: AggregationFormula) -> Self {
        formula.expr.to_string()
    }
}

/// Represents a formula that coalesces metrics from multiple components.
///
/// This is typically used for non-aggregating metrics like AC voltage or
/// frequency.
#[derive(Debug, Clone, PartialEq)]
pub struct CoalesceFormula {
    expr: Expr,
}

impl From<Expr> for CoalesceFormula {
    fn from(expr: Expr) -> Self {
        CoalesceFormula { expr }
    }
}

impl From<CoalesceFormula> for Expr {
    fn from(formula: CoalesceFormula) -> Self {
        formula.expr
    }
}

impl CoalesceFormula {
    pub(crate) fn new(expr: Expr) -> Self {
        CoalesceFormula { expr }
    }
}

impl std::fmt::Display for CoalesceFormula {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.expr.fmt(f)
    }
}

impl From<CoalesceFormula> for String {
    fn from(formula: CoalesceFormula) -> Self {
        formula.expr.to_string()
    }
}
