name: Component Graph CI

on:
  push:
    branches: [ v0.x.x ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Print environment (debug)
        run: env

      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        uses: frequenz-floss/gh-action-cargo-test@v1.0.0
